Backport $ZOTERO_REPOS_DIR and $ZOTERO_PROFILE

diff --git a/scripts/build_and_run b/scripts/build_and_run
--- a/scripts/build_and_run
+++ b/scripts/build_and_run
@@ -1,7 +1,23 @@
 #!/bin/bash -e
 
-# To use a custom Zotero profile, enter its name here
-PROFILE=""
+# Set ZOTERO_REPOS_DIR to use directory other than $HOME for zotero-client and zotero-standalone-build
+if [ -n "${ZOTERO_REPOS_DIR:-}" ]; then
+	repos_dir=$ZOTERO_REPOS_DIR
+else
+	repos_dir=$HOME
+fi
+
+for dir in zotero-client zotero-standalone-build; do
+	if [ ! -d "$repos_dir/$dir" ]; then
+		echo "$repos_dir/$dir not found" >&2
+		exit 1
+	fi
+done
+
+# Set ZOTERO_PROFILE environment variable to choose profile
+if [ -n "${ZOTERO_PROFILE:-}" ]; then
+	profile="-p $ZOTERO_PROFILE"
+fi
 
 REBUILD=0
 SKIP_BUNDLED_FILES=0
@@ -27,10 +43,6 @@ while getopts "rbd" opt; do
 	esac
 done
 
-if [ -n "$PROFILE" ]; then
-	PROFILE="-p $PROFILE"
-fi
-
 if [ $REBUILD -eq 1 ]; then
 	PARAMS=""
 	if [ $DEBUGGER -eq 1 ]; then
@@ -42,12 +54,12 @@ if [ $REBUILD -eq 1 ]; then
 	if ! ps u | grep scripts/build.js | grep -v grep > /dev/null; then
 		echo "Running JS build process"
 		echo
-		cd ~/zotero-client
+		cd $repos_dir/zotero-client
 		npm run build
 		echo
 	fi
 	
-	~/zotero-standalone-build/scripts/dir_build $PARAMS
+	$repos_dir/zotero-standalone-build/scripts/dir_build $PARAMS
 fi
 
 PARAMS=""
@@ -70,4 +82,4 @@ else
 	exit 1
 fi
 
-~/zotero-standalone-build/staging/$command $PROFILE -ZoteroDebugText -jsconsole $PARAMS "$@"
+$repos_dir/zotero-standalone-build/staging/$command $profile -ZoteroDebugText -jsconsole $PARAMS "$@"
