Add support for remote debugging via devtools server
devtools files are packaged in the browser/omni.ja, which we don't
include. This changes fetch_xulrunner.sh to extract them to a directory
in the Firefox package and adds a -t flag to build.sh that copies the
files into the build and adds prefs to allow the debugging server on
port 6100 and disable the prompt. (scripts/dir_build also now has a -t
flag.)

A flag to start the debugging server at runtime is coming in a separate
commit.

diff --git a/scripts/dir_build b/scripts/dir_build
--- a/scripts/dir_build
+++ b/scripts/dir_build
@@ -5,6 +5,20 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 ROOT_DIR="$(dirname "$SCRIPT_DIR")"
 . "$ROOT_DIR/config.sh"
 
+DEVTOOLS=0
+while getopts "t" opt; do
+	case $opt in
+		t)
+			DEVTOOLS=1
+			;;
+		
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+	esac
+done
+
 if [ "`uname`" = "Darwin" ]; then
 	PLATFORM="m"
 elif [ "`uname`" = "Linux" ]; then
@@ -20,6 +34,11 @@ if [ $VERSION = "4.0" ]; then
 	"$ZOTERO_BUILD_DIR/xpi/build_xpi_4.0" "$ZOTERO_SOURCE_DIR" $CHANNEL
 	"$ROOT_DIR/build.sh" -f "$ZOTERO_BUILD_DIR/xpi/build/zotero-build.xpi" -p $PLATFORM -c $CHANNEL -s
 else
+	PARAMS=""
+	if [ $DEVTOOLS -eq 1 ]; then
+		PARAMS="-t"
+	fi
+	
 	"$ZOTERO_BUILD_DIR/xpi/build_xpi" -s "$ZOTERO_SOURCE_DIR" -c $CHANNEL
-	"$ROOT_DIR/build.sh" -d "$ZOTERO_BUILD_DIR/xpi/build/staging" -p $PLATFORM -c $CHANNEL -s
+	"$ROOT_DIR/build.sh" -d "$ZOTERO_BUILD_DIR/xpi/build/staging" -p $PLATFORM -c $CHANNEL -s $PARAMS
 fi
